spring:
  datasource:
    url: jdbc:h2:mem:refund-idempotency
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE